server:
  port: 10010
  tomcat:
    max-threads: 100

spring:
  profiles:
    active: dev
    include: log-dev
  application:
    name: ics-parking-syl
  datasource:
    url: jdbc:sqlserver://192.168.4.76:1433;databaseName=syl_stop_car
    username: SA
    password: 1Q2w3e4r5t6y&U
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  redis:
    database: 0
    host: 192.168.4.71
    password: 123456
    port: 6379
  flyway:
    # 启动/禁用
    enabled: true
    # 禁止清理数据库表
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用,将当前数据库初始版本设置为0
    baseline-version: 0
    # 假如已经执行了版本1和版本3，如果增加了一个版本2，下面这个选项将会允许执行版本2的脚本
    out-of-order: false
    # 迁移文件地址 flyway默认地址为 db/migration ,可根据需求自行配置
    #locations: classpath:db/migration/prod
  cloud:
    consul:
      host: 192.168.4.76
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        tags: ics,parking,syl
        health-check-critical-timeout: 15m
        health-check-interval: 15s
        health-check-path: /actuator/health
        preferIpAddress: true

logging:
  level:
    cec.ics: debug
#--------- 健康检查配置 Start----------#
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#--------- 健康检查配置 End------------#
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#---------- mybatis-plus START----------#
mybatis-plus:
  mapper-locations:
    - classpath:cec/ics/module/mapper/xml/*.xml
  configuration:
    global-config:
      db-config:
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
        table-prefix: cec_  #表名前缀
#---------- mybatis-plus END------------#

pagehelper:
  helper-dialect: mysql
  reasonable: false
  #自动分页，为true时，若参数带有pageNum,pageSize,即使不调用PageHelper.startPage(1,10)，也会自动拼接limit
  supportMethodsArguments: false
  params: count=countSql

#--------------外部系统地址----------------
#ics-cloud请求地址
ics.url: http://192.168.4.31:8083
#布防撤防指令下发请求地址
ics.orderDown.url: http://192.168.3.248:8192
#通过设备id获取设备信息
ics.getPoint.url: http://192.168.4.31:8083
#获取告警信息
ics.getAlarm.url: http://192.168.4.31:10000/cec-alarm

#----------------------------------------

#---------------信息点类型id---------------------
#照明开关信息点id
lighting.openOrClose.pointInfoTypeId: 52f76846129111ea84c9a4bf015958d5

#----------------其他固定信息--------------------
#照明开关
lighting.open: 1
lighting.close: 0


